/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sweet_house;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author JayodyaRupasinghe
 */
public class foodlistaud extends javax.swing.JFrame {

    /**
     * Creates new form foodlistaud
     */
    
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    
    public foodlistaud() {
        super("Food List");
        initComponents();
        conn = dbconnection.connection();
        showfoodlist();
    }
    public void clear()
    {
                    txtfcode.setText("");
                    txtfname.setText("");
                    txtfprice.setText("");
    }
    public void showfoodlist()
    {
        try
        {
            st=conn.createStatement();
            String qry = "SELECT * FROM foodlist;";
            
            rs = st.executeQuery(qry);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
           // JOptionPane.showMessageDialog(null,"Successfull");
        }
        catch(Exception e)
                {
                     JOptionPane.showMessageDialog(null,e);
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblfoodlist = new javax.swing.JLabel();
        lblcategory = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblfcode = new javax.swing.JLabel();
        lblfname = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        txtfcode = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtfprice = new javax.swing.JTextField();
        butadd = new javax.swing.JButton();
        butclear = new javax.swing.JButton();
        butupdate = new javax.swing.JButton();
        butdelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitemlout = new javax.swing.JMenuItem();
        mitemexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblfoodlist.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblfoodlist.setText("                         Food List");

        lblcategory.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblcategory.setText("Display Food by Category");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shorties", "Burgers", "Buns", "Breads", "Spanchi Cakes", "Cakes", "Sweets(Domestic)", "Biscuits", "Beverages", "Toffees", "Birthday Items", "Hot Hut Foods" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblfcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblfcode.setText("Food Code");

        lblfname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblfname.setText("Food Name");

        lblprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblprice.setText("Price");

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });

        butadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/add.png"))); // NOI18N
        butadd.setText("ADD");
        butadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaddActionPerformed(evt);
            }
        });

        butclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/but3.png"))); // NOI18N
        butclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butclearActionPerformed(evt);
            }
        });

        butupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/but4.png"))); // NOI18N
        butupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butupdateActionPerformed(evt);
            }
        });

        butdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/but2.png"))); // NOI18N
        butdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdeleteActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Food Code", "Food Name", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(0).setHeaderValue("No");
            jTable1.getColumnModel().getColumn(1).setMinWidth(100);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(700);
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Food Code");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Food Name");
            jTable1.getColumnModel().getColumn(3).setMinWidth(200);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(700);
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Price");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblfoodlist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblcategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(butupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(butdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfcode)
                            .addComponent(lblfname)
                            .addComponent(lblprice))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfprice)
                            .addComponent(txtfname)
                            .addComponent(txtfcode, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butadd)
                            .addComponent(butclear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblfoodlist, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblcategory)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butdelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butupdate)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfcode)
                            .addComponent(txtfcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butadd))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblfname)
                                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblprice)))
                            .addComponent(butclear))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        jMenu1.setText("File");

        mitemlout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logout.png"))); // NOI18N
        mitemlout.setText("Log Out");
        mitemlout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemloutActionPerformed(evt);
            }
        });
        jMenu1.add(mitemlout);

        mitemexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/fsd.png"))); // NOI18N
        mitemexit.setText("Exit");
        mitemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemexitActionPerformed(evt);
            }
        });
        jMenu1.add(mitemexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Food List");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void butaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaddActionPerformed
        // TODO add your handling code here:
        String no, fcode, fname, price;
               try
                {
                   //String itemselected = jComboBox1.getSelectedItem().toString();
                    
                    no=txtfcode.getText();
                    fcode=txtfcode.getText();
                    fname=txtfname.getText();
                    price=txtfprice.getText();
                    
                    st= conn.createStatement();
                    
                    String qry = "INSERT INTO foodlist (no,foodcode,foodname,price) VALUES ('"+no+"','"+fcode+"','"+fname+"','"+price+"')";
                    
                   st.executeUpdate(qry);
                   
                   JOptionPane.showMessageDialog(null,"Insertion is Successful!!...");
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Error");
                }
    
    
                  clear(); 
                 showfoodlist();     
    }//GEN-LAST:event_butaddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r= jTable1.getSelectedRow();
        String fcode=jTable1.getValueAt(r, 1).toString();
        String fname=jTable1.getValueAt(r,2).toString();
        String fprice=jTable1.getValueAt(r, 3).toString();
        

txtfcode.setText(fcode);
txtfname.setText(fname);
txtfprice.setText(fprice);

    }//GEN-LAST:event_jTable1MouseClicked

    private void butclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butclearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_butclearActionPerformed

    private void butupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butupdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        //Update Selected Row
    try
    {
        if (jTable1.getSelectedRowCount()==1)
        {
             String no=txtfcode.getText();
             String fcode=txtfcode.getText();
             String fname=txtfname.getText();
             String price=txtfprice.getText();
             
             st= conn.createStatement();
             
             String qry = "UPDATE foodlist SET foodcode='"+fcode+"', foodname='"+fname+"',price='"+price+"'";
             
             //set updated value on table row
             
             st.executeUpdate(qry);
             //tblModel.setValueAt(no, jTable1.getSelectedRow(),0);
             tblModel.setValueAt(fcode, jTable1.getSelectedRow(),1);
             tblModel.setValueAt(fname, jTable1.getSelectedRow(),2);
             tblModel.setValueAt(price, jTable1.getSelectedRow(),3);
             
             JFrame frame = new JFrame();
            
            if (JOptionPane.showConfirmDialog(frame, "Are you sure if you want to Update?","Sweet house & hot hut foods system",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
                
                
             //update message display
             JOptionPane.showMessageDialog(this,"Update Successfully...!!");
        }
        else
             if(jTable1.getRowCount()==0) 
            {
               //if table is empty
                JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else
             {
                 //if row is not selected or multiple rows are selected
                 JOptionPane.showMessageDialog(this,"Please selecte singal row for update");
             }
    }
    catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
        clear();
        
        
           
            
    }//GEN-LAST:event_butupdateActionPerformed

    private void butdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdeleteActionPerformed
        // TODO add your handling code here:
                DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        //Delete Selected Row
        
    try
    {
              
             String fcode=txtfcode.getText();
             String fname=txtfname.getText();
             String price=txtfprice.getText();
             
             
             tblModel.setValueAt(fcode, jTable1.getSelectedRow(),1);
             tblModel.setValueAt(fname, jTable1.getSelectedRow(),2);
             tblModel.setValueAt(price, jTable1.getSelectedRow(),3);
        
        st= conn.createStatement();
                    
        String qry = "DELETE FROM foodlist where foodcode='"+fcode+"'&& foodname='"+fname+"'&& price='"+price+"' ";
                    
        st.executeUpdate(qry);
                    
        if (jTable1.getSelectedRowCount()==1)
        {
            JFrame frame = new JFrame();
            
            if (JOptionPane.showConfirmDialog(frame, "Are you sure if you want to delete?","Sweet house & hot hut foods system",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
        //if singal row is selected than delete
            tblModel.removeRow(jTable1.getSelectedRow());
        }
            
        }
        else
        {
            if(jTable1.getRowCount()==0) 
            {
             // if table is empty (no data) than display message
            JOptionPane.showMessageDialog(this,"Table is Empty");
            }
            else
            {
                //if table is not empty but row is not selected or mmultiple row are selected.
                JOptionPane.showMessageDialog(this,"Please selecte singal row for delete");
            }
        }
    }
    catch(Exception e)
                {
                     JOptionPane.showMessageDialog(null,e);
                }
        
    clear();
    }//GEN-LAST:event_butdeleteActionPerformed

    private void mitemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemexitActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("EXIT");
 
        if (JOptionPane.showConfirmDialog(frame, "Are you sure if you want to exit?","Sweet House System",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
        System.exit(0);
        }
    }//GEN-LAST:event_mitemexitActionPerformed

    private void mitemloutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemloutActionPerformed
        // TODO add your handling code here:
        loginform lform = new loginform();
        if (JOptionPane.showConfirmDialog(lform, "Are you sure if you want to Logout?","Sweet House System",
   JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
              setVisible(false);
              lform.setVisible(true);
              this.dispose();
        }
    }//GEN-LAST:event_mitemloutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodlistaud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodlistaud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodlistaud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodlistaud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodlistaud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butadd;
    private javax.swing.JButton butclear;
    private javax.swing.JButton butdelete;
    private javax.swing.JButton butupdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblcategory;
    private javax.swing.JLabel lblfcode;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lblfoodlist;
    private javax.swing.JLabel lblprice;
    private javax.swing.JMenuItem mitemexit;
    private javax.swing.JMenuItem mitemlout;
    private javax.swing.JTextField txtfcode;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtfprice;
    // End of variables declaration//GEN-END:variables
}
