/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sweet_house;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author JayodyaRupasinghe
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form loginform
     */
    Connection conn=null;
    Statement st=null;
    ResultSet rs=null;
    
    
   
    
    public loginform() 
    {
        super("Login");
        initComponents();
        conn = dbconnection.connection();
        showdate();
        showtime();
    }
    public void showdate() 
    {

            
		java.util.Date d = new java.util.Date();
		SimpleDateFormat form = new SimpleDateFormat("yyyy-MM-dd");
		lbldate.setText(form.format(d));

    }

    public void showtime() 
    {

		new Timer(0, new ActionListener() 
                {
			@Override
			public void actionPerformed(ActionEvent e) 
                        {
				java.util.Date d = new java.util.Date();
				SimpleDateFormat form = new SimpleDateFormat("hh:mm:ss a");
				lbltime.setText(form.format(d));

			}
		}
                ).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblloginform = new javax.swing.JLabel();
        lbluname = new javax.swing.JLabel();
        lblpw = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        butlogin = new javax.swing.JButton();
        butcancel = new javax.swing.JButton();
        lblsystemname = new javax.swing.JLabel();
        lblcreateby = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        lbldate = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblloginform.setBackground(new java.awt.Color(0, 0, 0));
        lblloginform.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblloginform.setText("                        Login Form");

        lbluname.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbluname.setText("User Name:");

        lblpw.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblpw.setText("Password:");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jCheckBox1.setText("   Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        butlogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        butlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/but6.png"))); // NOI18N
        butlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butloginMouseClicked(evt);
            }
        });
        butlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butloginActionPerformed(evt);
            }
        });

        butcancel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        butcancel.setText("Cancel");

        lblsystemname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblsystemname.setText("Horana Sweet House & Hot hut foods System");

        lblcreateby.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcreateby.setText("Copyright  by : JR Technology");

        lbldate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        lbltime.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblloginform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(lblsystemname))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(lblcreateby))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(butlogin)
                                    .addGap(84, 84, 84)
                                    .addComponent(butcancel))
                                .addComponent(jCheckBox1)
                                .addComponent(lblpw)
                                .addComponent(lbluname)
                                .addComponent(txtuname)
                                .addComponent(jPasswordField1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbldate, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblloginform, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbltime, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lbldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(lbluname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblpw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butlogin)
                    .addComponent(butcancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblsystemname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblcreateby)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butloginActionPerformed

    private void butloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butloginMouseClicked
        // TODO add your handling code here:
        
        try
        {
            st = conn.createStatement();
            String uname=txtuname.getText();
            String pword = jPasswordField1.getText();
            
            String qry= "SELECT * FROM login WHERE un='" + uname + "' && pw = '" + pword + "'";
            
            rs= st.executeQuery(qry);
            if (rs.next()) 
            {
                JOptionPane.showMessageDialog(null, "Login Successfully!!!! ");
                setVisible(false);
                workwindow wwindow = new workwindow();
                wwindow.setVisible(true);
                this.dispose();
                
            }
            else 
            {

                JOptionPane.showMessageDialog(null, "Invalid Credentials ");
            }
        }
        catch(Exception e)
                {
                    
                }// TODO add your handling code here:        // TODO add your handling code here:
                       
    
    }//GEN-LAST:event_butloginMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        /*if(jCheckBox1.isSelected()== true)
        {
            jPasswordField1.setEchoChar((char)0);
            
        }
        else
        {
            String pw = jPasswordField1.getText();
            
            char[] ch = new char[pw.length()];
            
            int count=0;
            for (int i = 0; i < ch.length; i++) 
            {
               count++ ;
                
            }
            
            System.out.print(count);
            jPasswordField1.setText("*");
            
            
            
        }*/
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butcancel;
    private javax.swing.JButton butlogin;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblcreateby;
    private javax.swing.JLabel lbldate;
    private javax.swing.JLabel lblloginform;
    private javax.swing.JLabel lblpw;
    private javax.swing.JLabel lblsystemname;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel lbluname;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
